### PR TITLE
Backport ASN1_TIME_diff for libressl/pre-1.0.2-OpenSSL

### PR DESCRIPTION
**Pull request by jameshilliard**

### CODE REVIEW

**Comment by cminyard** [comment]
A few of comments on this:

You don't mention where you ported this from, but it's a big enough chunk of code that there are licensing issues.  The source of the code needs to be documented, and the original license needs to be covered.  If it's from openssl, for instance, I don't think the license is compatible with GPL.

Other users may need this.  But I'm not sure where to stick this.

It makes me nervous to even supply the ability to compile with that old a version of openssl.  I don't know anything about libressl, looking it appears to be maintained.

IMHO this really belongs in libressl.  I'm not sure how feasible that is.

**Comment by jameshilliard** [comment]
> You don't mention where you ported this from, but it's a big enough chunk of code that there are licensing issues. The source of the code needs to be documented, and the original license needs to be covered. If it's from openssl, for instance, I don't think the license is compatible with GPL.

It was a backport and looked to essentially be the extracted from openssl, since you're already linking against openssl this at least shouldn't make a difference regarding licensing since GPLv2 doesn't have a linking exception.

> It makes me nervous to even supply the ability to compile with that old a version of openssl. I don't know anything about libressl, looking it appears to be maintained.

Yeah, it's maintained, they just went a different direction regarding newer API's, but this older API should be maintained indefinitely for the most part at least when it comes to security fixes and such.

> IMHO this really belongs in libressl. I'm not sure how feasible that is.

I agree, but that's rather unlikely as I'm pretty sure they consider this particular part of the API to be in permanent maintenance only mode for the most part. They are apparently keeping this API around for backwards compatibility but are not following openssl's newer changes.

**Comment by cminyard** [comment]
On Mon, Jul 05, 2021 at 09:20:21AM -0700, James Hilliard wrote:
> > You don't mention where you ported this from, but it's a big enough chunk of code that there are licensing issues. The source of the code needs to be documented, and the original license needs to be covered. If it's from openssl, for instance, I don't think the license is compatible with GPL.
> 
> It was a backport and looked to essentially be the extracted from openssl, since you're already linking against openssl this at least shouldn't make a difference regarding licensing since GPLv2 doesn't have a linking exception.

gtlssh is GPLv2, but there's all sorts of legal haziness around linking
against other libraries.  So I'm not sure.  There is a special exception
in gensio for linking against OpenSSL that the Debian group had me add.
My understanding is that dynamic linking from GPLv2 to OpenSSL with the
special added exception is ok (and obviously others think that way), but
taking out a piece of code and adding it somewhere else is something
different that I'm not sure about.  I am not comfortable with that.

Either way, if you just included it like you did, that's relicensing the
code, and removing provinence, and I'm fairly sure you can't do that.

I'm not exceptionally happy about the SSL library situation in general.
The situation is fairly messy.

**Comment by jameshilliard** [comment]
> My understanding is that dynamic linking from GPLv2 to OpenSSL with the special added exception is ok (and obviously others think that way), but taking out a piece of code and adding it somewhere else is something different that I'm not sure about. I am not comfortable with that.

So I re-backpacked it from the latest OpenSSL and moved it to a separate header file with the original license header from OpenSSL.

> Either way, if you just included it like you did, that's relicensing the
code, and removing provinence, and I'm fairly sure you can't do that.

Yeah, that should be fixed now.

> I'm not exceptionally happy about the SSL library situation in general.
> The situation is fairly messy.

Yeah, for sure.

**Comment by cminyard** [comment]
From https://www.apache.org/licenses/GPL-compatibility.html

Despite our best efforts, the FSF has never considered the Apache License to be compatible with GPL version 2, citing the patent termination and indemnification provisions as restrictions not present in the older GPL license. The Apache Software Foundation believes that you should always try to obey the constraints expressed by the copyright holder when redistributing their work.

IANAL, but if that's the way the FSF feels about this, it's not possible to take Apache licensed code into a FSF licensed project.  This is, unfortunately, messy business.  Oddly enough, they consider GPLv3 compatible.

Anyway, to work around this, I wrote some time code from scratch to handle the doing the time diff.  It's pushed into the master branch, the 2.2.x branch, and the v1.5.x branch.

**Comment by jameshilliard** [comment]
> Despite our best efforts, the FSF has never considered the Apache License to be compatible with GPL version 2, citing the patent termination and indemnification provisions as restrictions not present in the older GPL license.

Ah, I figured the OpenSSL linking exception would cover that since I pulled it out into an independent header. I wonder what the implications are for linking against the Apache2 licensed OpenSSLv3 will be. I guess the distinction isn't particularly clear. I suppose making gensio GPLv2+ licensed may make things clearer regarding compatibility but not sure if that's something that would make sense to do.

> IANAL, but if that's the way the FSF feels about this, it's not possible to take Apache licensed code into a FSF licensed project. This is, unfortunately, messy business. Oddly enough, they consider GPLv3 compatible.

My understanding was that you could at least merge Apache2 into GPLv3 code since they licenses are compatible, but the Apache Foundation rules(which are different from the Apache2 license rules) don't allow merging GPLv3 code into Apache2 since doing so would make the combination effectively GPLv3.

> This is, unfortunately, messy business.

Yeah, would have been easier if they did dual MIT/Apache2.

> Anyway, to work around this, I wrote some time code from scratch to handle the doing the time diff.

Great

**Pull request closed without merging**
