### PR TITLE
Add configure option to disable man page installation.

### LINKED ISSUE #14: gensio should have a way to disable man page installation
As gensio/ser2net is frequently used on embedded systems there should be a way to disable man page installation in autoconf to reduce the installed size.

### PR DESCRIPTION
**Pull request by jameshilliard**
Something along these lines should fix #14.

### CODE REVIEW

**Comment by cminyard** [comment]
I took something like this that I redid.  You can't remove the man pages from EXTRA_DIST or DIST_SUBDIRS or the "make dist" option won't work correctly.

**Comment by jameshilliard** [comment]
That seems to work for me with buildroot, we should also add a flag to disable tests and another to disable examples, do you want to do that or should I send pull requests?

**Comment by cminyard** [comment]
On Sun, Apr 12, 2020 at 12:46:27PM -0700, James Hilliard wrote:
> That seems to work for me with buildroot, we should also add a flag to disable tests and another to disable examples, do you want to do that or should I send pull requests?

Well, they don't get installed, so it's not as big a deal as the man
pages.  The tests do not get built without running "make check", so they
don't matter at all.

If you really want to, you can submit a patch to not compile the
examples.

BTW, you really ought to consider using yocto for builds.  There is a
learning curve, but it's much more flexible and has a lot of content
already available.

-corey

**Comment by jameshilliard** [comment]
> BTW, you really ought to consider using yocto for builds.

Yeah, I've looked at it before but found it less maintainable than buildroot.

**Pull request closed without merging**
