### PR TITLE
configure.ac: add --with-tests option

### PR DESCRIPTION
**Pull request by ffontaine**
Allow the user to disable tests through --without-tests, this is
especially useful on embedded systems

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by cminyard** [comment]
I'm trying to figure out why this is useful.  Do the tests not build?  If the tests build, it is fairly standard to build them.

Plus, you have an error here, you shouldn't modify DIST_SUBDIRS, otherwise the tests might not get included in the distribution.  If you really need this you need to fix that.

**Comment by ffontaine** [comment]
Indeed tests fail to build on systems without pthread because oomtest.c includes pthread.h unconditionally: 

```
oomtest.c:22:10: fatal error: pthread.h: No such file or directory
 #include <pthread.h>
          ^~~~~~~~~~~
```
More information can be found here: http://autobuild.buildroot.org/?reason=gensio-1.4.1

An other possibility would be to avoid building oomtest without pthreads. What solution do you prefer?

**Comment by cminyard** [comment]
On Mon, Feb 10, 2020 at 09:55:57AM -0800, Fabrice Fontaine wrote:
> Indeed tests fail to build on systems without pthread because oomtest.c includes pthread.h unconditionally: 
> 
> ```
> oomtest.c:22:10: fatal error: pthread.h: No such file or directory
>  #include <pthread.h>
>           ^~~~~~~~~~~
> ```
> More information can be found here: http://autobuild.buildroot.org/?reason=gensio-1.4.1
> 
> An other possibility would be to avoid building oomtest without pthreads. What solution do you prefer?

Yeah, my preference would be to make it work with threads disabled.
That's a bit much to ask you to do, and I should have handled that,
so I went ahead and did it.  It's pushed into git now under the tag
v1.5.1.  I'll get a release on sourceforge ser2net site soon.

What OS are you using that doesn't have posix threads?  More curious
than anything.

-corey

**Comment by ffontaine** [comment]
Build failures was raised on arm1176jzf-s architecture and an uclibc toolchain configured without threads (http://autobuild.buildroot.org/toolchains/tarballs/br-arm11-full-nothread-2019.11.tar.bz2)

**Comment by ffontaine** [comment]
Moreover, 1.5.1 still fails to build without threads because -lpthread is added unconditionally to oomtest_LDADD in tests/Makefile.am. It should be removed as -lpthread is already added to LIBS by configure.ac if threads are available and enabled (see #11).

**Comment by cminyard** [comment]
On Tue, Feb 11, 2020 at 10:22:11AM -0800, Fabrice Fontaine wrote:
> Moreover, 1.5.1 still fails to build without threads because -lpthread is added unconditionally to oomtest_LDADD in tests/Makefile.am. It should be removed as -lpthread is already added to LIBS by configure.ac if threads are available and enabled (see #11).

Dang it, my bad.  Is that the only issue?  I wasn't sure what to do with
the file you referenced previously.  It appears to be some sort of build
target.

-corey

**Comment by ffontaine** [comment]
Yes, with #11, everything builds fine.

**Pull request closed without merging**
